//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Draft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public string Filters { get; set; }
<<<<<<< Updated upstream
=======

        private static int currentId = 5756;

        public Items()
        {

        }

        public Items(string name)
        {
            Id = currentId++;
            Name = name;
            Quantity = 1;
            Filters = "NONE";
        }
>>>>>>> Stashed changes
    }
}
