//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Draft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public string Filters { get; set; }

        public Items(string name, string filters)
        {
            Name = name;
            Number = 1;
            // TODO implement adding filters
            filters.Split(',');
        }

        public Items()
        {
        }

        ~Items()
        {
        }
        void Add()
        {
            Number++;
        }

        void Remove()
        {
            if (Number > 0) Number--;
        }
    }
}
